### ISSUE TITLE
BUG: record.msg is being rendered without clearing args

### ISSUE THREAD

**Issue by shahar-medigate** [wkeeling/ratelimitingfilter#12]
https://github.com/wkeeling/ratelimitingfilter/blob/eaa18ec8e37c2ef22c2ba1c16bb10918a3fe7de7/ratelimitingfilter/ratelimitingfilter.py#L73

By using `getMessage()`, you are omitting any formatting parameter, this will cause an issue when the logger uses args

For example: `logger.info("Example: %s", "text")` will be rendered twice while the second time it will be something similar to
`"Example: text" % ("text",)`

In order to fix this, you only need to set `record.args` to an empty tuple

**Comment by wkeeling** [comment]
Many thanks for raising this. 

I'm not entirely sure how that problem slipped through, but it's now fixed. Thanks again.
