### ISSUE TITLE
Filter breaks with TypeError on logger.exception

### ISSUE THREAD

**Issue by adam-ra** [wkeeling/ratelimitingfilter#3]
TypeError: unsupported operand type(s) for +=: 'ConnectionError' and 'str'

**Comment by adam-ra** [comment]
Sorry, my mistake -- I incorrectly logged exceptions.

**Comment by wkeeling** [comment]
No problem - although I think `logger.exception(e)` is probably a common case, and the filter ought not to fall over with a `TypeError` when used like that. I'll perhaps look at making that more robust. Thanks for raising the issue in the first instance!
